// Generated by Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import Foundation;
@import AVFoundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ChatCampUIKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class AvatarView;
@class MessageContainerView;
@class UILabel;
@class UIImageView;
@class NSCoder;
@class UICollectionViewLayoutAttributes;
@class UIGestureRecognizer;

SWIFT_CLASS("_TtC13ChatCampUIKit25MessageCollectionViewCell")
@interface MessageCollectionViewCell : UICollectionViewCell
+ (NSString * _Nonnull)reuseIdentifier SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MessageCollectionViewCell.reuseIdentifier()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) AvatarView * _Nonnull avatarView SWIFT_DEPRECATED_OBJC("Swift property 'MessageCollectionViewCell.avatarView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) MessageContainerView * _Nonnull messageContainerView SWIFT_DEPRECATED_OBJC("Swift property 'MessageCollectionViewCell.messageContainerView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UILabel * _Nonnull cellTopLabel SWIFT_DEPRECATED_OBJC("Swift property 'MessageCollectionViewCell.cellTopLabel' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UILabel * _Nonnull cellBottomLabel SWIFT_DEPRECATED_OBJC("Swift property 'MessageCollectionViewCell.cellBottomLabel' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIImageView * _Nonnull cellBottomReadReceiptImage SWIFT_DEPRECATED_OBJC("Swift property 'MessageCollectionViewCell.cellBottomReadReceiptImage' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setupSubviews SWIFT_DEPRECATED_OBJC("Swift method 'MessageCollectionViewCell.setupSubviews()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)prepareForReuse;
- (void)applyLayoutAttributes:(UICollectionViewLayoutAttributes * _Nonnull)layoutAttributes;
/// Handle tap gesture on contentView and its subviews like messageContainerView, cellTopLabel, cellBottomLabel, avatarView ….
- (void)handleTapGesture:(UIGestureRecognizer * _Nonnull)gesture SWIFT_DEPRECATED_OBJC("Swift method 'MessageCollectionViewCell.handleTapGesture(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Handle long press gesture, return true when gestureRecognizer’s touch point in <code>messageContainerView</code>’s frame
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer SWIFT_WARN_UNUSED_RESULT;
/// Handle <code>ContentView</code>‘s tap gesture, return false when <code>ContentView</code> doesn’t needs to handle gesture
- (BOOL)cellContentViewWithCanHandle:(CGPoint)touchPoint SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MessageCollectionViewCell.cellContentView(canHandle:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


SWIFT_CLASS("_TtC13ChatCampUIKit16AudioMessageCell")
@interface AudioMessageCell : MessageCollectionViewCell
+ (NSString * _Nonnull)reuseIdentifier SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIFont;
@class UIColor;
@class UIImage;

SWIFT_CLASS("_TtC13ChatCampUIKit10AvatarView")
@interface AvatarView : UIImageView
@property (nonatomic, copy) NSString * _Nullable initials SWIFT_DEPRECATED_OBJC("Swift property 'AvatarView.initials' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIFont * _Nonnull placeholderFont SWIFT_DEPRECATED_OBJC("Swift property 'AvatarView.placeholderFont' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIColor * _Nonnull placeholderTextColor SWIFT_DEPRECATED_OBJC("Swift property 'AvatarView.placeholderTextColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) CGFloat fontMinimumScaleFactor SWIFT_DEPRECATED_OBJC("Swift property 'AvatarView.fontMinimumScaleFactor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) BOOL adjustsFontSizeToFitWidth SWIFT_DEPRECATED_OBJC("Swift property 'AvatarView.adjustsFontSizeToFitWidth' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) CGRect frame;
@property (nonatomic) CGRect bounds;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage SWIFT_UNAVAILABLE;
@end

@class NSBundle;

SWIFT_CLASS("_TtC13ChatCampUIKit26BlockedUsersViewController")
@interface BlockedUsersViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIScrollView;

@interface BlockedUsersViewController (SWIFT_EXTENSION(ChatCampUIKit))
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end

@class UITableView;

@interface BlockedUsersViewController (SWIFT_EXTENSION(ChatCampUIKit)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UITableViewCell;

@interface BlockedUsersViewController (SWIFT_EXTENSION(ChatCampUIKit)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end



@class MessagesCollectionView;
@class MessageInputBar;
@class UIView;

SWIFT_CLASS("_TtC13ChatCampUIKit22MessagesViewController")
@interface MessagesViewController : UIViewController
/// The <code>MessagesCollectionView</code> managed by the messages view controller object.
@property (nonatomic, strong) MessagesCollectionView * _Nonnull messagesCollectionView SWIFT_DEPRECATED_OBJC("Swift property 'MessagesViewController.messagesCollectionView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The <code>MessageInputBar</code> used as the <code>inputAccessoryView</code> in the view controller.
@property (nonatomic, strong) MessageInputBar * _Nonnull messageInputBar SWIFT_DEPRECATED_OBJC("Swift property 'MessagesViewController.messageInputBar' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// A Boolean value that determines whether the <code>MessagesCollectionView</code> scrolls to the
/// bottom whenever the <code>InputTextView</code> begins editing.
/// The default value of this property is <code>false</code>.
@property (nonatomic) BOOL scrollsToBottomOnKeybordBeginsEditing SWIFT_DEPRECATED_OBJC("Swift property 'MessagesViewController.scrollsToBottomOnKeybordBeginsEditing' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// A Boolean value that determines whether the <code>MessagesCollectionView</code>
/// maintains it’s current position when the height of the <code>MessageInputBar</code> changes.
/// The default value of this property is <code>false</code>.
@property (nonatomic) BOOL maintainPositionOnKeyboardFrameChanged SWIFT_DEPRECATED_OBJC("Swift property 'MessagesViewController.maintainPositionOnKeyboardFrameChanged' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) BOOL canBecomeFirstResponder;
@property (nonatomic, readonly, strong) UIView * _Nullable inputAccessoryView;
@property (nonatomic, readonly) BOOL shouldAutorotate;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ChatCampUIKit18ChatViewController")
@interface ChatViewController : MessagesViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface ChatViewController (SWIFT_EXTENSION(ChatCampUIKit))
- (void)connectionDidChangeWithIsConnected:(BOOL)isConnected SWIFT_DEPRECATED_OBJC("Swift method 'ChatViewController.connectionDidChange(isConnected:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end

@class UIDocumentInteractionController;

@interface ChatViewController (SWIFT_EXTENSION(ChatCampUIKit)) <UIDocumentInteractionControllerDelegate>
- (UIViewController * _Nonnull)documentInteractionControllerViewControllerForPreview:(UIDocumentInteractionController * _Nonnull)controller SWIFT_WARN_UNUSED_RESULT;
@end

@class AVAudioRecorder;

@interface ChatViewController (SWIFT_EXTENSION(ChatCampUIKit)) <AVAudioRecorderDelegate>
- (void)audioRecorderDidFinishRecording:(AVAudioRecorder * _Nonnull)recorder successfully:(BOOL)flag;
@end




@interface ChatViewController (SWIFT_EXTENSION(ChatCampUIKit))
- (void)didTapMessageIn:(MessageCollectionViewCell * _Nonnull)cell SWIFT_DEPRECATED_OBJC("Swift method 'ChatViewController.didTapMessage(in:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end




@interface ChatViewController (SWIFT_EXTENSION(ChatCampUIKit))
- (void)messageInputBar:(MessageInputBar * _Nonnull)inputBar didPressSendButtonWith:(NSString * _Nonnull)text SWIFT_DEPRECATED_OBJC("Swift method 'ChatViewController.messageInputBar(_:didPressSendButtonWith:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)messageInputBar:(MessageInputBar * _Nonnull)inputBar textViewTextDidChangeTo:(NSString * _Nonnull)text SWIFT_DEPRECATED_OBJC("Swift method 'ChatViewController.messageInputBar(_:textViewTextDidChangeTo:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end



@class UIDocumentMenuViewController;
@class UIDocumentPickerViewController;

@interface ChatViewController (SWIFT_EXTENSION(ChatCampUIKit)) <UIDocumentMenuDelegate, UIDocumentPickerDelegate>
- (void)documentMenu:(UIDocumentMenuViewController * _Nonnull)documentMenu didPickDocumentPicker:(UIDocumentPickerViewController * _Nonnull)documentPicker;
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)controller didPickDocumentAtURL:(NSURL * _Nonnull)url;
- (void)documentPickerWasCancelled:(UIDocumentPickerViewController * _Nonnull)controller;
- (void)documentMenuWasCancelled:(UIDocumentMenuViewController * _Nonnull)documentMenu;
@end




@interface ChatViewController (SWIFT_EXTENSION(ChatCampUIKit))
- (NSInteger)numberOfMessagesIn:(MessagesCollectionView * _Nonnull)messagesCollectionView SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'ChatViewController.numberOfMessages(in:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end




@interface ChatViewController (SWIFT_EXTENSION(ChatCampUIKit))
- (void)loadMessagesFromAPI SWIFT_DEPRECATED_OBJC("Swift method 'ChatViewController.loadMessagesFromAPI()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


SWIFT_CLASS("_TtC13ChatCampUIKit17CustomMessageCell")
@interface CustomMessageCell : MessageCollectionViewCell
+ (NSString * _Nonnull)reuseIdentifier SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ChatCampUIKit19DocumentMessageCell")
@interface DocumentMessageCell : MessageCollectionViewCell
+ (NSString * _Nonnull)reuseIdentifier SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ChatCampUIKit27GroupChannelsViewController")
@interface GroupChannelsViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface GroupChannelsViewController (SWIFT_EXTENSION(ChatCampUIKit))
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end




@interface GroupChannelsViewController (SWIFT_EXTENSION(ChatCampUIKit))
- (void)connectionDidChangeWithIsConnected:(BOOL)isConnected SWIFT_DEPRECATED_OBJC("Swift method 'GroupChannelsViewController.connectionDidChange(isConnected:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface GroupChannelsViewController (SWIFT_EXTENSION(ChatCampUIKit)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface GroupChannelsViewController (SWIFT_EXTENSION(ChatCampUIKit)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end



@class InputTextView;

/// A InputItem that inherits from UIButton
/// <h2>Important Notes</h2>
/// <ol>
///   <li>
///     Intended to be used in an <code>InputStackView</code>
///   </li>
/// </ol>
SWIFT_CLASS("_TtC13ChatCampUIKit18InputBarButtonItem")
@interface InputBarButtonItem : UIButton
/// A weak reference to the MessageInputBar that the InputBarButtonItem used in
@property (nonatomic, weak) MessageInputBar * _Nullable messageInputBar SWIFT_DEPRECATED_OBJC("Swift property 'InputBarButtonItem.messageInputBar' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) CGSize intrinsicContentSize;
/// The title for the UIControlState.normal
@property (nonatomic, copy) NSString * _Nullable title SWIFT_DEPRECATED_OBJC("Swift property 'InputBarButtonItem.title' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The image for the UIControlState.normal
@property (nonatomic, strong) UIImage * _Nullable image SWIFT_DEPRECATED_OBJC("Swift property 'InputBarButtonItem.image' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Calls the onSelectedAction or onDeselectedAction when set
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
/// Calls the onEnabledAction or onDisabledAction when set
@property (nonatomic, getter=isEnabled) BOOL enabled;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// Sets up the default properties
- (void)setup SWIFT_DEPRECATED_OBJC("Swift method 'InputBarButtonItem.setup()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Used to setup your own initial properties
/// \param item A reference to Self
///
///
/// returns:
/// Self
- (nonnull instancetype)configure:(SWIFT_NOESCAPE void (^ _Nonnull)(InputBarButtonItem * _Nonnull))item SWIFT_DEPRECATED_OBJC("Swift method 'InputBarButtonItem.configure(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Sets the onKeyboardEditingBeginsAction
/// \param action The new onKeyboardEditingBeginsAction
///
///
/// returns:
/// Self
- (nonnull instancetype)onKeyboardEditingBegins:(void (^ _Nonnull)(InputBarButtonItem * _Nonnull))action SWIFT_DEPRECATED_OBJC("Swift method 'InputBarButtonItem.onKeyboardEditingBegins(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Sets the onKeyboardEditingEndsAction
/// \param action The new onKeyboardEditingEndsAction
///
///
/// returns:
/// Self
- (nonnull instancetype)onKeyboardEditingEnds:(void (^ _Nonnull)(InputBarButtonItem * _Nonnull))action SWIFT_DEPRECATED_OBJC("Swift method 'InputBarButtonItem.onKeyboardEditingEnds(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Sets the onTextViewDidChangeAction
/// \param action The new onTextViewDidChangeAction
///
///
/// returns:
/// Self
- (nonnull instancetype)onTextViewDidChange:(void (^ _Nonnull)(InputBarButtonItem * _Nonnull, InputTextView * _Nonnull))action SWIFT_DEPRECATED_OBJC("Swift method 'InputBarButtonItem.onTextViewDidChange(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Sets the onTouchUpInsideAction
/// \param action The new onTouchUpInsideAction
///
///
/// returns:
/// Self
- (nonnull instancetype)onTouchUpInside:(void (^ _Nonnull)(InputBarButtonItem * _Nonnull))action SWIFT_DEPRECATED_OBJC("Swift method 'InputBarButtonItem.onTouchUpInside(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Sets the onSelectedAction
/// \param action The new onSelectedAction
///
///
/// returns:
/// Self
- (nonnull instancetype)onSelected:(void (^ _Nonnull)(InputBarButtonItem * _Nonnull))action SWIFT_DEPRECATED_OBJC("Swift method 'InputBarButtonItem.onSelected(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Sets the onDeselectedAction
/// \param action The new onDeselectedAction
///
///
/// returns:
/// Self
- (nonnull instancetype)onDeselected:(void (^ _Nonnull)(InputBarButtonItem * _Nonnull))action SWIFT_DEPRECATED_OBJC("Swift method 'InputBarButtonItem.onDeselected(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Sets the onEnabledAction
/// \param action The new onEnabledAction
///
///
/// returns:
/// Self
- (nonnull instancetype)onEnabled:(void (^ _Nonnull)(InputBarButtonItem * _Nonnull))action SWIFT_DEPRECATED_OBJC("Swift method 'InputBarButtonItem.onEnabled(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Sets the onDisabledAction
/// \param action The new onDisabledAction
///
///
/// returns:
/// Self
- (nonnull instancetype)onDisabled:(void (^ _Nonnull)(InputBarButtonItem * _Nonnull))action SWIFT_DEPRECATED_OBJC("Swift method 'InputBarButtonItem.onDisabled(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Executes the onTextViewDidChangeAction with the given textView
/// \param textView A reference to the InputTextView
///
- (void)textViewDidChangeActionWith:(InputTextView * _Nonnull)textView SWIFT_DEPRECATED_OBJC("Swift method 'InputBarButtonItem.textViewDidChangeAction(with:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Executes the onKeyboardEditingEndsAction
- (void)keyboardEditingEndsAction SWIFT_DEPRECATED_OBJC("Swift method 'InputBarButtonItem.keyboardEditingEndsAction()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Executes the onKeyboardEditingBeginsAction
- (void)keyboardEditingBeginsAction SWIFT_DEPRECATED_OBJC("Swift method 'InputBarButtonItem.keyboardEditingBeginsAction()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Executes the onTouchUpInsideAction
- (void)touchUpInsideAction;
/// An InputBarButtonItem that’s spacing property is set to be .flexible
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) InputBarButtonItem * _Nonnull flexibleSpace SWIFT_DEPRECATED_OBJC("Swift property 'InputBarButtonItem.flexibleSpace' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (InputBarButtonItem * _Nonnull)flexibleSpace SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'InputBarButtonItem.flexibleSpace' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// An InputBarButtonItem that’s spacing property is set to be .fixed with the width arguement
+ (InputBarButtonItem * _Nonnull)fixedSpace:(CGFloat)width SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'InputBarButtonItem.fixedSpace(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


/// A UIStackView that’s intended for holding <code>InputBarButtonItem</code>s
/// <h2>Important Notes</h2>
/// <ol>
///   <li>
///     Default alignment is .fill
///   </li>
///   <li>
///     Default distribution is .fill
///   </li>
///   <li>
///     The distribution property needs to be based on its arranged subviews intrinsicContentSize so it is not recommended to change it
///   </li>
/// </ol>
SWIFT_CLASS("_TtC13ChatCampUIKit14InputStackView")
@interface InputStackView : UIStackView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
/// Sets up the default properties
- (void)setup SWIFT_DEPRECATED_OBJC("Swift method 'InputStackView.setup()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end

@class NSAttributedString;
@class NSTextContainer;

/// A UITextView that has a UILabel embedded for placeholder text
/// <h2>Important Notes</h2>
/// <ol>
///   <li>
///     Changing the font, textAlignment or textContainerInset automatically performs the same modifications to the placeholderLabel
///   </li>
///   <li>
///     Intended to be used in an <code>MessageInputBar</code>
///   </li>
///   <li>
///     Default placeholder text is “New Message”
///   </li>
///   <li>
///     Will pass a pasted image it’s <code>MessageInputBar</code>’s <code>InputManager</code>s
///   </li>
/// </ol>
SWIFT_CLASS("_TtC13ChatCampUIKit13InputTextView")
@interface InputTextView : UITextView
@property (nonatomic, copy) NSString * _Null_unspecified text;
@property (nonatomic, strong) NSAttributedString * _Null_unspecified attributedText;
/// The images that are currently stored as NSTextAttachment’s
@property (nonatomic, readonly, copy) NSArray<UIImage *> * _Nonnull images SWIFT_DEPRECATED_OBJC("Swift property 'InputTextView.images' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, copy) NSArray * _Nonnull components SWIFT_DEPRECATED_OBJC("Swift property 'InputTextView.components' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) BOOL isImagePasteEnabled SWIFT_DEPRECATED_OBJC("Swift property 'InputTextView.isImagePasteEnabled' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// A UILabel that holds the InputTextView’s placeholder text
@property (nonatomic, readonly, strong) UILabel * _Nonnull placeholderLabel SWIFT_DEPRECATED_OBJC("Swift property 'InputTextView.placeholderLabel' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The placeholder text that appears when there is no text. The default value is “New Message”
@property (nonatomic, copy) NSString * _Nullable placeholder SWIFT_DEPRECATED_OBJC("Swift property 'InputTextView.placeholder' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The placeholderLabel’s textColor
@property (nonatomic, strong) UIColor * _Nullable placeholderTextColor SWIFT_DEPRECATED_OBJC("Swift property 'InputTextView.placeholderTextColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The UIEdgeInsets the placeholderLabel has within the InputTextView
@property (nonatomic) UIEdgeInsets placeholderLabelInsets SWIFT_DEPRECATED_OBJC("Swift property 'InputTextView.placeholderLabelInsets' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The font of the InputTextView. When set the placeholderLabel’s font is also updated
@property (nonatomic, strong) UIFont * _Null_unspecified font;
/// The textAlignment of the InputTextView. When set the placeholderLabel’s textAlignment is also updated
@property (nonatomic) NSTextAlignment textAlignment;
@property (nonatomic) UIEdgeInsets scrollIndicatorInsets;
/// A weak reference to the MessageInputBar that the InputTextView is contained within
@property (nonatomic, weak) MessageInputBar * _Nullable messageInputBar SWIFT_DEPRECATED_OBJC("Swift property 'InputTextView.messageInputBar' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// Sets up the default properties
- (void)setup SWIFT_DEPRECATED_OBJC("Swift method 'InputTextView.setup()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (BOOL)canPerformAction:(SEL _Nonnull)action withSender:(id _Nullable)sender SWIFT_WARN_UNUSED_RESULT;
- (void)paste:(id _Nullable)sender;
@end

@class UIActivityIndicatorView;

SWIFT_CLASS("_TtC13ChatCampUIKit19LocationMessageCell")
@interface LocationMessageCell : MessageCollectionViewCell
+ (NSString * _Nonnull)reuseIdentifier SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) UIActivityIndicatorView * _Nonnull activityIndicator SWIFT_DEPRECATED_OBJC("Swift property 'LocationMessageCell.activityIndicator' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIImageView * _Nonnull imageView SWIFT_DEPRECATED_OBJC("Swift property 'LocationMessageCell.imageView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)setupSubviews;
- (void)setupConstraints SWIFT_DEPRECATED_OBJC("Swift method 'LocationMessageCell.setupConstraints()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)prepareForReuse;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class PlayButtonView;

SWIFT_CLASS("_TtC13ChatCampUIKit16MediaMessageCell")
@interface MediaMessageCell : MessageCollectionViewCell
+ (NSString * _Nonnull)reuseIdentifier SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) PlayButtonView * _Nonnull playButtonView SWIFT_DEPRECATED_OBJC("Swift property 'MediaMessageCell.playButtonView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIImageView * _Nonnull imageView SWIFT_DEPRECATED_OBJC("Swift property 'MediaMessageCell.imageView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)setupConstraints SWIFT_DEPRECATED_OBJC("Swift method 'MediaMessageCell.setupConstraints()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)setupSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13ChatCampUIKit20MessageContainerView")
@interface MessageContainerView : UIImageView
@property (nonatomic) CGRect frame;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ChatCampUIKit17MessageHeaderView")
@interface MessageHeaderView : UICollectionReusableView
+ (NSString * _Nonnull)reuseIdentifier SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MessageHeaderView.reuseIdentifier()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ChatCampUIKit21MessageDateHeaderView")
@interface MessageDateHeaderView : MessageHeaderView
+ (NSString * _Nonnull)reuseIdentifier SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) UILabel * _Nonnull dateLabel SWIFT_DEPRECATED_OBJC("Swift property 'MessageDateHeaderView.dateLabel' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13ChatCampUIKit17MessageFooterView")
@interface MessageFooterView : UICollectionReusableView
+ (NSString * _Nonnull)reuseIdentifier SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MessageFooterView.reuseIdentifier()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@class UIVisualEffectView;
@class SeparatorLine;
@class UITraitCollection;

/// A powerful InputAccessoryView ideal for messaging applications
SWIFT_CLASS("_TtC13ChatCampUIKit15MessageInputBar")
@interface MessageInputBar : UIView
/// The background UIView anchored to the bottom, left, and right of the MessageInputBar
/// with a top anchor equal to the bottom of the top InputStackView
@property (nonatomic, strong) UIView * _Nonnull backgroundView SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.backgroundView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// A content UIView that holds the left/right/bottom InputStackViews and InputTextView. Anchored to the bottom of the
/// topStackView and inset by the padding UIEdgeInsets
@property (nonatomic, strong) UIView * _Nonnull contentView SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.contentView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// A UIVisualEffectView that adds a blur effect to make the view appear transparent.
/// <h2>Important Notes</h2>
/// <ol>
///   <li>
///     The blurView is initially not added to the backgroundView to improve performance when not needed. When <code>isTranslucent</code> is set to TRUE for the first time the blurView is added and anchored to the <code>backgroundView</code>s edge anchors
///   </li>
/// </ol>
@property (nonatomic, strong) UIVisualEffectView * _Nonnull blurView SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.blurView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Determines if the MessageInputBar should have a translucent effect
@property (nonatomic) BOOL isTranslucent SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.isTranslucent' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// A SeparatorLine that is anchored at the top of the MessageInputBar with a height of 1
@property (nonatomic, readonly, strong) SeparatorLine * _Nonnull separatorLine SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.separatorLine' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The InputStackView at the InputStackView.top position
/// <h2>Important Notes</h2>
/// <ol>
///   <li>
///     It’s axis is initially set to .vertical
///   </li>
///   <li>
///     It’s alignment is initially set to .fill
///   </li>
/// </ol>
@property (nonatomic, readonly, strong) InputStackView * _Nonnull topStackView SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.topStackView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The InputStackView at the InputStackView.left position
/// <h2>Important Notes</h2>
/// <ol>
///   <li>
///     It’s axis is initially set to .horizontal
///   </li>
/// </ol>
@property (nonatomic, readonly, strong) InputStackView * _Nonnull leftStackView SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.leftStackView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The InputStackView at the InputStackView.right position
/// <h2>Important Notes</h2>
/// <ol>
///   <li>
///     It’s axis is initially set to .horizontal
///   </li>
/// </ol>
@property (nonatomic, readonly, strong) InputStackView * _Nonnull rightStackView SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.rightStackView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The InputStackView at the InputStackView.bottom position
/// <h2>Important Notes</h2>
/// <ol>
///   <li>
///     It’s axis is initially set to .horizontal
///   </li>
///   <li>
///     It’s spacing is initially set to 15
///   </li>
/// </ol>
@property (nonatomic, readonly, strong) InputStackView * _Nonnull bottomStackView SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.bottomStackView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The InputTextView a user can input a message in
@property (nonatomic, strong) InputTextView * _Nonnull inputTextView SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.inputTextView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// A InputBarButtonItem used as the send button and initially placed in the rightStackView
@property (nonatomic, strong) InputBarButtonItem * _Nonnull sendButton SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.sendButton' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The anchor constants that inset the contentView
/// \code
/// V:|...[InputStackView.top]-(padding.top)-[contentView]-(padding.bottom)-|
///
/// H:|-(padding.left)-[contentView]-(padding.right)-|
///
/// \endcode
@property (nonatomic) UIEdgeInsets padding SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.padding' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The anchor constants used by the top InputStackView
/// <h2>Important Notes</h2>
/// <ol>
///   <li>
///     The topStackViewPadding.bottom property is not used. Use padding.top to add separation
///   </li>
/// </ol>
/// \code
/// V:|-(topStackViewPadding.top)-[InputStackView.top]-(padding.top)-[InputTextView]-...|
///
/// H:|-(topStackViewPadding.left)-[InputStackView.top]-(topStackViewPadding.right)-|
///
/// \endcode
@property (nonatomic) UIEdgeInsets topStackViewPadding SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.topStackViewPadding' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The anchor constants used by the InputStackView
/// \code
/// V:|...-(padding.top)-(textViewPadding.top)-[InputTextView]-(textViewPadding.bottom)-[InputStackView.bottom]-...|
///
/// H:|...-[InputStackView.left]-(textViewPadding.left)-[InputTextView]-(textViewPadding.right)-[InputStackView.right]-...|
///
/// \endcode
@property (nonatomic) UIEdgeInsets textViewPadding SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.textViewPadding' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Returns the most recent size calculated by <code>calculateIntrinsicContentSize()</code>
@property (nonatomic, readonly) CGSize intrinsicContentSize;
/// A boolean that indicates if the maxTextViewHeight has been met. Keeping track of this
/// improves the performance
@property (nonatomic, readonly) BOOL isOverMaxTextViewHeight SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.isOverMaxTextViewHeight' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// A boolean that determines if the maxTextViewHeight should be auto updated on device rotation
@property (nonatomic) BOOL shouldAutoUpdateMaxTextViewHeight SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.shouldAutoUpdateMaxTextViewHeight' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The maximum height that the InputTextView can reach
@property (nonatomic) CGFloat maxTextViewHeight SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.maxTextViewHeight' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The height that will fit the current text in the InputTextView based on its current bounds
@property (nonatomic, readonly) CGFloat requiredInputTextViewHeight SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.requiredInputTextViewHeight' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The fixed widthAnchor constant of the leftStackView
@property (nonatomic, readonly) CGFloat leftStackViewWidthConstant SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.leftStackViewWidthConstant' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The fixed widthAnchor constant of the rightStackView
@property (nonatomic, readonly) CGFloat rightStackViewWidthConstant SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.rightStackViewWidthConstant' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The InputBarItems held in the leftStackView
@property (nonatomic, readonly, copy) NSArray<InputBarButtonItem *> * _Nonnull leftStackViewItems SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.leftStackViewItems' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The InputBarItems held in the rightStackView
@property (nonatomic, readonly, copy) NSArray<InputBarButtonItem *> * _Nonnull rightStackViewItems SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.rightStackViewItems' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The InputBarItems held in the bottomStackView
@property (nonatomic, readonly, copy) NSArray<InputBarButtonItem *> * _Nonnull bottomStackViewItems SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.bottomStackViewItems' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The InputBarItems held in the topStackView
@property (nonatomic, readonly, copy) NSArray<InputBarButtonItem *> * _Nonnull topStackViewItems SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.topStackViewItems' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// The InputBarItems held to make use of their hooks but they are not automatically added to a UIStackView
@property (nonatomic, copy) NSArray<InputBarButtonItem *> * _Nonnull nonStackViewItems SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.nonStackViewItems' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Returns a flatMap of all the items in each of the UIStackViews
@property (nonatomic, readonly, copy) NSArray<InputBarButtonItem *> * _Nonnull items SWIFT_DEPRECATED_OBJC("Swift property 'MessageInputBar.items' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)didMoveToWindow;
/// Sets up the default properties
- (void)setup SWIFT_DEPRECATED_OBJC("Swift method 'MessageInputBar.setup()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Invalidates the view’s intrinsic content size
- (void)invalidateIntrinsicContentSize;
/// Calculates the correct intrinsicContentSize of the MessageInputBar. This takes into account the various padding edge
/// insets, InputTextView’s height and top/bottom InputStackView’s heights.
///
/// returns:
/// The required intrinsicContentSize
- (CGSize)calculateIntrinsicContentSize SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MessageInputBar.calculateIntrinsicContentSize()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Returns the max height the InputTextView can grow to based on the UIScreen
///
/// returns:
/// Max Height
- (CGFloat)calculateMaxTextViewHeight SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MessageInputBar.calculateMaxTextViewHeight()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Sets the leftStackViewWidthConstant
/// \param newValue New widthAnchor constant
///
/// \param animated If the layout should be animated
///
- (void)setLeftStackViewWidthConstantTo:(CGFloat)newValue animated:(BOOL)animated SWIFT_DEPRECATED_OBJC("Swift method 'MessageInputBar.setLeftStackViewWidthConstant(to:animated:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Sets the rightStackViewWidthConstant
/// \param newValue New widthAnchor constant
///
/// \param animated If the layout should be animated
///
- (void)setRightStackViewWidthConstantTo:(CGFloat)newValue animated:(BOOL)animated SWIFT_DEPRECATED_OBJC("Swift method 'MessageInputBar.setRightStackViewWidthConstant(to:animated:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Invalidates the intrinsicContentSize
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
/// Enables/Disables the sendButton based on the InputTextView’s text being empty
/// Calls each items <code>textViewDidChangeAction</code> method
/// Calls the delegates <code>textViewTextDidChangeTo</code> method
/// Invalidates the intrinsicContentSize
- (void)textViewDidChange;
/// Calls each items <code>keyboardEditingBeginsAction</code> method
/// Invalidates the intrinsicContentSize so that the keyboard does not overlap the view
- (void)textViewDidBeginEditing;
/// Calls each items <code>keyboardEditingEndsAction</code> method
- (void)textViewDidEndEditing;
/// Calls the delegates <code>didPressSendButtonWith</code> method
/// Assumes that the InputTextView’s text has been set to empty and calls <code>inputTextViewDidChange()</code>
/// Invalidates each of the inputManagers
- (void)didSelectSendButton SWIFT_DEPRECATED_OBJC("Swift method 'MessageInputBar.didSelectSendButton()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


SWIFT_CLASS("_TtC13ChatCampUIKit12MessageLabel")
@interface MessageLabel : UILabel
@property (nonatomic, strong) NSAttributedString * _Nullable attributedText;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, strong) UIFont * _Null_unspecified font;
@property (nonatomic, strong) UIColor * _Null_unspecified textColor;
@property (nonatomic) NSLineBreakMode lineBreakMode;
@property (nonatomic) NSInteger numberOfLines;
@property (nonatomic) NSTextAlignment textAlignment;
@property (nonatomic) UIEdgeInsets textInsets SWIFT_DEPRECATED_OBJC("Swift property 'MessageLabel.textInsets' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSDictionary<NSAttributedStringKey, id> * _Nonnull defaultAttributes SWIFT_DEPRECATED_OBJC("Swift property 'MessageLabel.defaultAttributes' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (NSDictionary<NSAttributedStringKey, id> * _Nonnull)defaultAttributes SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'MessageLabel.defaultAttributes' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)setDefaultAttributes:(NSDictionary<NSAttributedStringKey, id> * _Nonnull)value SWIFT_DEPRECATED_OBJC("Swift property 'MessageLabel.defaultAttributes' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, copy) NSDictionary<NSAttributedStringKey, id> * _Nonnull addressAttributes SWIFT_DEPRECATED_OBJC("Swift property 'MessageLabel.addressAttributes' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, copy) NSDictionary<NSAttributedStringKey, id> * _Nonnull dateAttributes SWIFT_DEPRECATED_OBJC("Swift property 'MessageLabel.dateAttributes' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, copy) NSDictionary<NSAttributedStringKey, id> * _Nonnull phoneNumberAttributes SWIFT_DEPRECATED_OBJC("Swift property 'MessageLabel.phoneNumberAttributes' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, copy) NSDictionary<NSAttributedStringKey, id> * _Nonnull urlAttributes SWIFT_DEPRECATED_OBJC("Swift property 'MessageLabel.urlAttributes' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)drawTextInRect:(CGRect)rect;
- (void)configureWithBlock:(SWIFT_NOESCAPE void (^ _Nonnull)(void))block SWIFT_DEPRECATED_OBJC("Swift method 'MessageLabel.configure(block:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end

@class UICollectionViewLayout;

SWIFT_CLASS("_TtC13ChatCampUIKit22MessagesCollectionView")
@interface MessagesCollectionView : UICollectionView
@property (nonatomic) NSTimeInterval showsDateHeaderAfterTimeInterval SWIFT_DEPRECATED_OBJC("Swift property 'MessagesCollectionView.showsDateHeaderAfterTimeInterval' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithFrame:(CGRect)frame collectionViewLayout:(UICollectionViewLayout * _Nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init;
- (void)handleTapGesture:(UIGestureRecognizer * _Nonnull)gesture;
- (void)scrollToBottomWithAnimated:(BOOL)animated SWIFT_DEPRECATED_OBJC("Swift method 'MessagesCollectionView.scrollToBottom(animated:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)reloadDataAndKeepOffset SWIFT_DEPRECATED_OBJC("Swift method 'MessagesCollectionView.reloadDataAndKeepOffset()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end



@class UICollectionViewLayoutInvalidationContext;

/// The layout object used by <code>MessagesCollectionView</code> to determine the size of all
/// framework provided <code>MessageCollectionViewCell</code> subclasses.
SWIFT_CLASS("_TtC13ChatCampUIKit32MessagesCollectionViewFlowLayout")
@interface MessagesCollectionViewFlowLayout : UICollectionViewFlowLayout
/// Font to be used by <code>TextMessageCell</code> for <code>MessageData.text(String)</code> case.
/// The default value of this property is <code>UIFont.preferredFont(forTextStyle: .body)</code>
@property (nonatomic, strong) UIFont * _Nonnull messageLabelFont SWIFT_DEPRECATED_OBJC("Swift property 'MessagesCollectionViewFlowLayout.messageLabelFont' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Determines the maximum number of <code>MessageCollectionViewCell</code> attributes to cache.
/// The default value of this property is 500.
@property (nonatomic) NSInteger attributesCacheMaxSize SWIFT_DEPRECATED_OBJC("Swift property 'MessagesCollectionViewFlowLayout.attributesCacheMaxSize' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// A type property representing the <code>MessagesCollectionViewLayoutAttributes</code> to be used.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layoutAttributesClass;)
+ (Class _Nonnull)layoutAttributesClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// Removes the cached layout information for a <code>MessageType</code> given its <code>messageId</code>.
/// \param messageId The <code>messageId</code> for the <code>MessageType</code> whose cached layout information is to be removed.
///
- (void)removeCachedAttributesFor:(NSString * _Nonnull)messageId SWIFT_DEPRECATED_OBJC("Swift method 'MessagesCollectionViewFlowLayout.removeCachedAttributes(for:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Removes the cached layout information for all <code>MessageType</code>s.
- (void)removeAllCachedAttributes SWIFT_DEPRECATED_OBJC("Swift method 'MessagesCollectionViewFlowLayout.removeAllCachedAttributes()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)newBounds SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewLayoutInvalidationContext * _Nonnull)invalidationContextForBoundsChange:(CGRect)newBounds SWIFT_WARN_UNUSED_RESULT;
- (NSArray<UICollectionViewLayoutAttributes *> * _Nullable)layoutAttributesForElementsInRect:(CGRect)rect SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewLayoutAttributes * _Nullable)layoutAttributesForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
/// The size for the <code>MessageCollectionViewCell</code> considering all of the cell’s contents.
/// \param indexPath The <code>IndexPath</code> of the cell.
///
- (CGSize)sizeForItemAt:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'MessagesCollectionViewFlowLayout.sizeForItem(at:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end
















@interface MessagesCollectionViewFlowLayout (SWIFT_EXTENSION(ChatCampUIKit))
/// A Boolean value that determines if the <code>AvatarView</code> is always on the leading
/// side of a MessageCollectionViewCell.
/// Setting this property to <code>true</code> causes <code>avatarAlwaysTrailing</code> to be set to <code>false</code>.
/// The default value of this property is <code>false</code>.
@property (nonatomic, readonly) BOOL avatarAlwaysLeading SWIFT_DEPRECATED_OBJC("Swift property 'MessagesCollectionViewFlowLayout.avatarAlwaysLeading' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// A Boolean value that determines if the <code>AvatarView</code> is always on the trailing
/// side of a <code>MessageCollectionViewCell</code>.
/// Setting this property to <code>true</code> causes <code>avatarAlwaysLeading</code> to be set to <code>false</code>.
/// The default value of this property is <code>false</code>.
@property (nonatomic, readonly) BOOL avatarAlwaysTrailing SWIFT_DEPRECATED_OBJC("Swift property 'MessagesCollectionViewFlowLayout.avatarAlwaysTrailing' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end



@interface MessagesViewController (SWIFT_EXTENSION(ChatCampUIKit))
/// A Boolean value that determines whether the <code>MessagesCollectionView</code> scrolls to the
/// bottom on the view’s first layout.
/// The default value of this property is <code>false</code>.
@property (nonatomic, readonly) BOOL scrollsToBottomOnFirstLayout SWIFT_DEPRECATED_OBJC("Swift property 'MessagesViewController.scrollsToBottomOnFirstLayout' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface MessagesViewController (SWIFT_EXTENSION(ChatCampUIKit)) <UICollectionViewDataSource>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UICollectionReusableView * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView viewForSupplementaryElementOfKind:(NSString * _Nonnull)kind atIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end




@interface MessagesViewController (SWIFT_EXTENSION(ChatCampUIKit)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout referenceSizeForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout referenceSizeForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldShowMenuForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView canPerformAction:(SEL _Nonnull)action forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Nullable)sender SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView performAction:(SEL _Nonnull)action forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Nullable)sender;
@end






@interface NSObject (SWIFT_EXTENSION(ChatCampUIKit))
+ (NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'NSObject.string()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull nameOfClass SWIFT_DEPRECATED_OBJC("Swift property 'NSObject.nameOfClass' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (NSString * _Nonnull)nameOfClass SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'NSObject.nameOfClass' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


SWIFT_CLASS("_TtC13ChatCampUIKit26OpenChannelsViewController")
@interface OpenChannelsViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface OpenChannelsViewController (SWIFT_EXTENSION(ChatCampUIKit))
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end


@interface OpenChannelsViewController (SWIFT_EXTENSION(ChatCampUIKit)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface OpenChannelsViewController (SWIFT_EXTENSION(ChatCampUIKit)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13ChatCampUIKit14PlayButtonView")
@interface PlayButtonView : UIView
@property (nonatomic, readonly, strong) UIView * _Nonnull triangleView SWIFT_DEPRECATED_OBJC("Swift property 'PlayButtonView.triangleView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


/// A UIView thats intrinsicContentSize is overrided so an exact height can be specified
/// <h2>Important Notes</h2>
/// <ol>
///   <li>
///     Default height is 1.0
///   </li>
///   <li>
///     Default backgroundColor is UIColor.lightGray
///   </li>
///   <li>
///     Intended to be used in an <code>InputStackView</code>
///   </li>
/// </ol>
SWIFT_CLASS("_TtC13ChatCampUIKit13SeparatorLine")
@interface SeparatorLine : UIView
/// The height of the line
@property (nonatomic) CGFloat height SWIFT_DEPRECATED_OBJC("Swift property 'SeparatorLine.height' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// Sets up the default properties
- (void)setup SWIFT_DEPRECATED_OBJC("Swift method 'SeparatorLine.setup()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


SWIFT_CLASS("_TtC13ChatCampUIKit15TextMessageCell")
@interface TextMessageCell : MessageCollectionViewCell
+ (NSString * _Nonnull)reuseIdentifier SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) MessageLabel * _Nonnull messageLabel SWIFT_DEPRECATED_OBJC("Swift property 'TextMessageCell.messageLabel' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)applyLayoutAttributes:(UICollectionViewLayoutAttributes * _Nonnull)layoutAttributes;
- (void)prepareForReuse;
- (void)setupSubviews;
/// Handle <code>ContentView</code>‘s tap gesture, return false when <code>ContentView</code> don’t needs to handle gesture
- (BOOL)cellContentViewWithCanHandle:(CGPoint)touchPoint SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




@interface UIImageView (SWIFT_EXTENSION(ChatCampUIKit))
- (void)setImageForNameWithString:(NSString * _Nonnull)string backgroundColor:(UIColor * _Nullable)backgroundColor circular:(BOOL)circular textAttributes:(NSDictionary<NSAttributedStringKey, id> * _Nullable)textAttributes gradient:(BOOL)gradient SWIFT_DEPRECATED_OBJC("Swift method 'UIImageView.setImageForName(string:backgroundColor:circular:textAttributes:gradient:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end








@interface UIViewController (SWIFT_EXTENSION(ChatCampUIKit))
- (void)showAlertWithTitle:(NSString * _Nonnull)title message:(NSString * _Nonnull)message actionText:(NSString * _Nonnull)actionText SWIFT_DEPRECATED_OBJC("Swift method 'UIViewController.showAlert(title:message:actionText:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end

@class UINavigationController;

@interface UIViewController (SWIFT_EXTENSION(ChatCampUIKit))
+ (UINavigationController * _Nonnull)homeTabBarNavigationController SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'UIViewController.homeTabBarNavigationController()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (BlockedUsersViewController * _Nonnull)blockedUsersViewController SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'UIViewController.blockedUsersViewController()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface NSUserDefaults (SWIFT_EXTENSION(ChatCampUIKit))
- (NSString * _Nullable)userID SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'UserDefaults.userID()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)setUserIDWithUserID:(NSString * _Nullable)userID SWIFT_DEPRECATED_OBJC("Swift method 'UserDefaults.setUserID(userID:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (NSString * _Nullable)username SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'UserDefaults.username()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)setUsernameWithUsername:(NSString * _Nullable)username SWIFT_DEPRECATED_OBJC("Swift method 'UserDefaults.setUsername(username:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (NSString * _Nullable)deviceToken SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'UserDefaults.deviceToken()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)setDeviceTokenWithDeviceToken:(NSString * _Nullable)deviceToken SWIFT_DEPRECATED_OBJC("Swift method 'UserDefaults.setDeviceToken(deviceToken:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


SWIFT_CLASS("_TtC13ChatCampUIKit19UsersViewController")
@interface UsersViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UsersViewController (SWIFT_EXTENSION(ChatCampUIKit))
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end


@interface UsersViewController (SWIFT_EXTENSION(ChatCampUIKit)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface UsersViewController (SWIFT_EXTENSION(ChatCampUIKit)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13ChatCampUIKit18WritingMessageCell")
@interface WritingMessageCell : MessageCollectionViewCell
+ (NSString * _Nonnull)reuseIdentifier SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
